esphome:
  name: esphome05
  friendly_name: cyb01

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "your_ota_password"

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esphome05 Fallback Hotspot"
    password: !secret wifi_password

psram:

time:
  - platform: homeassistant
    id: ha_time

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

font:
  - file: "Roboto-Bold.ttf"
    id: font_large
    size: 36
  - file: "Roboto-Medium.ttf"
    id: font_medium
    size: 24
  - file: "Roboto-Regular.ttf"
    id: font_small
    size: 16
  - file: "Roboto-Regular.ttf"
    id: font_tiny
    size: 12

sensor:
  - platform: homeassistant
    id: comed_price
    entity_id: sensor.comed_5_minute_price

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.openweathermap_feels_like_temperature

  - platform: homeassistant
    id: office_temp
    entity_id: sensor.smartthings_button_temperature

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

text_sensor:
  - platform: homeassistant
    id: hvac_state
    entity_id: climate.great_room
    attribute: hvac_action

binary_sensor:
  - platform: homeassistant
    id: front_door
    entity_id: binary_sensor.front_entrance_contact

  - platform: homeassistant
    id: garage_door
    entity_id: binary_sensor.garage_entrance_contact

  - platform: homeassistant
    id: patio_door
    entity_id: binary_sensor.patio_entrance_contact

display:
  - platform: ili9xxx
    model: TFT_2.4
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO33
    color_palette: 8BIT
    rotation: 90
    update_interval: 5s
    lambda: |-
      it.fill(COLOR_OFF);

      it.strftime(160, 10, id(font_large), TextAlign::TOP_CENTER, "%I:%M %p", id(ha_time).now());
      it.strftime(160, 50, id(font_small), TextAlign::TOP_CENTER, "%A, %B %d", id(ha_time).now());

      it.line(10, 80, 310, 80);

      int y = 95;
      it.print(10, y, id(font_medium), "Electric:");
      if (id(comed_price).has_state()) {
        it.printf(310, y, id(font_medium), TextAlign::TOP_RIGHT, "%.1fc", id(comed_price).state);
      }

      y += 35;
      it.print(10, y, id(font_medium), "Temp:");
      if (id(office_temp).has_state()) {
        it.printf(160, y, id(font_medium), TextAlign::TOP_CENTER, "In: %.1fF", id(office_temp).state);
      }
      if (id(outdoor_temp).has_state()) {
        it.printf(310, y, id(font_medium), TextAlign::TOP_RIGHT, "Out: %.1fF", id(outdoor_temp).state);
      }

      y += 35;
      it.print(10, y, id(font_medium), "HVAC:");
      if (id(hvac_state).has_state() && id(hvac_state).state != "unavailable") {
        it.printf(310, y, id(font_medium), TextAlign::TOP_RIGHT, "%s", id(hvac_state).state.c_str());
      }

      y += 30;
      it.line(10, y, 310, y);

      y += 10;
      it.print(10, y, id(font_small), "Doors:");
      y += 20;

      auto front_color = id(front_door).state ? Color(255, 0, 0) : Color(0, 255, 0);
      it.printf(10, y, id(font_tiny), front_color, "Front: %s", id(front_door).state ? "OPEN" : "Closed");

      auto garage_color = id(garage_door).state ? Color(255, 0, 0) : Color(0, 255, 0);
      it.printf(120, y, id(font_tiny), garage_color, "Garage: %s", id(garage_door).state ? "OPEN" : "Closed");

      auto patio_color = id(patio_door).state ? Color(255, 0, 0) : Color(0, 255, 0);
      it.printf(230, y, id(font_tiny), patio_color, "Patio: %s", id(patio_door).state ? "OPEN" : "Closed");

touchscreen:
  - platform: xpt2046
    id: my_touchscreen
    cs_pin: GPIO25
    interrupt_pin: GPIO36
    update_interval: 50ms
    calibration:
      x_min: 200
      x_max: 3900
      y_min: 200
      y_max: 3900
    on_touch:
      - light.toggle: back_light

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm

  - platform: gpio
    pin: GPIO4
    id: onboard_led_gpio

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

  - platform: binary
    output: onboard_led_gpio
    name: "Board LED"
    id: board_led
    restore_mode: ALWAYS_OFF

button:
  - platform: restart
    name: "Restart"
